//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLaba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int AnimalID { get; set; }
        public string Species { get; set; }
        public int Age { get; set; }
        public int Farm_id { get; set; }
    
        public virtual Farm Farm { get; set; }
    }
}
