//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLaba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int ExpenseID { get; set; }
        public string ExpenseType { get; set; }
        public decimal Amount { get; set; }
        public int Farm_id { get; set; }
    
        public virtual Farm Farm { get; set; }
    }
}
